services:
  - type: web
    name: noithat-api
    runtime: node
    plan: free
    region: singapore
    rootDir: DATN/server
    buildCommand: npm install --include=dev && npm run build && npm run placeholders && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://noithat-web-l9d3.onrender.com
      - key: STORAGE_DRIVER
        value: local


  - type: web
    name: noithat-web
    runtime: static
    rootDir: DATN/client
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://noithat-api-0w0f.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
